[GLOBAL]
pants_version = "2.19.1"

backend_packages = [
    "pants.backend.python",
    "pants.backend.python.lint.pylint",
    "pants.backend.python.lint.black",
    "pants.backend.python.lint.isort",
    "pants.backend.python.typecheck.mypy",
]

pants_ignore = [
    "*/",

    "!opentelemetry-api/",
    "!opentelemetry-api/**",

    "!test-dist-info/",
    "!test-dist-info/**",

    "!tests/",
    "!tests/opentelemetry-test-utils/",
    "!tests/opentelemetry-test-utils/**",

    "!3rdparty/",
    "!3rdparty/**",
]

[python]
interpreter_constraints = ["CPython>=3.8, <3.12"]
enable_resolves = true

[python.resolves]
python-default = "3rdparty/python/default.lock"
tools = "3rdparty/python/tools.lock"

[python.resolves_to_interpreter_constraints]
# Use a single python version for dev tooling
tools = ["CPython==3.11.*"]

[black]
install_from_resolve = "tools"

[isort]
install_from_resolve = "tools"

[pylint]
install_from_resolve = "tools"

[pytest]
install_from_resolve = "tools"

[mypy]
install_from_resolve = "tools"
config = "mypy.ini"
