[tool.pytest.ini_options]
addopts = "-rs -v"
log_cli = true

[tool.ruff]
# Minimum supported python version
target-version = "py38"

line-length = 79
extend-exclude = [
  # Ignore generated files
  "exporter/opentelemetry-exporter-zipkin-proto-http/src/opentelemetry/exporter/zipkin/proto/http/v2/gen",
  "*_pb2*.py*",
]

[tool.ruff.lint]
# Only lint for import sorting for now
select = [
  "I", # isort
]

[tool.ruff.lint.isort]
known-third-party = [
  "psutil",
  "pytest",
  "redis",
  "redis_opentracing",
  "opencensus",
]
known-first-party = ["opentelemetry", "opentelemetry_example_app"]
