version: '3'

volumes:
    prometheus_data: {}
    prometheus_data_demo1: {}
    grafana_data: {}

services:

  prometheus:
    image: prom/prometheus:v2.33.4
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data_demo1:/prometheus
    restart: unless-stopped
    expose:
      - 9090
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"

  grafana:
    image: grafana/grafana:8.4.3
    container_name: grafana
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
    restart: unless-stopped
    expose:
      - 3000
    network_mode: host
    labels:
      org.label-schema.group: "monitoring"
