{
 "title": "OpenTelemetry Day",
 "time": { "from": "now-2d", "to": "now" },
 "templating": {
  "list": [
   { "name": "rate_window", "query": "10s,1m,5m,10m,30m" }
  ]
 },
 "panels": [
  {
   "title": "system.cpu.time by label.state",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "sum without (cpu) (rate(system_cpu_time_s_total[$rate_window])) / ignoring(state) group_left sum without (cpu, state) (rate(system_cpu_time_s_total[$rate_window])) ",
     "legendFormat": "{{state}}"
    }
   ]
  },
  {
   "title": "Request Latency",
   "type": "heatmap",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "sum(rate(request_duration_s_bucket[$rate_window])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Request Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(request_duration_s_bucket[$rate_window])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(request_duration_s_bucket[$rate_window])) by (le))",
     "legendFormat": "p95"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(request_duration_s_bucket[$rate_window])) by (le))",
     "legendFormat": "p50"
    }
   ]
  }
 ]
}