receivers:
  otlp:
    protocols:
      grpc:
      http:

processors:
  batch:

extensions:
  zpages:


exporters:
  googlecloud:
    project: otel-starter-project

service:
  extensions: [zpages]

  pipelines:
    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [googlecloud]
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [googlecloud]
