# module(
#     name = "my-module",
#     version = "1.0",
# )

# See https://rules-python.readthedocs.io/en/latest/getting-started.html

# Update the version "0.0.0" to the release found here:
# https://github.com/bazelbuild/rules_python/releases.
bazel_dep(name = "rules_python", version = "1.0.0")

pip = use_extension("@rules_python//python/extensions:pip.bzl", "pip")
pip.parse(
    hub_name = "my_deps",
    python_version = "3.11",
    requirements_lock = "//:requirements.lock.txt",
)
use_repo(pip, "my_deps")
